// src/components/RouteViewer.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  
  export let routeGeoJson: string | null;
  export let raceName: string;
  
  let mapContainer: HTMLDivElement;
  let map: any;
  let L: any;
  
  onMount(async () => {
    if (!routeGeoJson) return;
    
    const leaflet = await import('leaflet');
    L = leaflet.default;
    
    map = L.map(mapContainer).setView([9.0, -79.5], 10);
    
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; OpenStreetMap contributors'
    }).addTo(map);
    
    try {
      const coords: [number, number][] = JSON.parse(routeGeoJson);
      
      if (coords.length > 0) {
        const polyline = L.polyline(coords, {
          color: '#FF6B00',
          weight: 4,
          opacity: 0.8
        }).addTo(map);
        
        map.fitBounds(polyline.getBounds(), { padding: [50, 50] });
        
        L.marker(coords[0], {
          icon: L.divIcon({
            className: 'marker-start',
            html: '<div class="w-4 h-4 bg-green-500 rounded-full border-2 border-white"></div>',
            iconSize: [16, 16]
          })
        }).addTo(map).bindPopup('Inicio');
        
        L.marker(coords[coords.length - 1], {
          icon: L.divIcon({
            className: 'marker-end',
            html: '<div class="w-4 h-4 bg-red-500 rounded-full border-2 border-white"></div>',
            iconSize: [16, 16]
          })
        }).addTo(map).bindPopup('Meta');
      }
    } catch (e) {
      console.error('Error loading route:', e);
    }
  });
  
  onDestroy(() => {
    if (map) {
      map.remove();
    }
  });
</script>

<div class="w-full h-96 rounded-lg overflow-hidden">
  <div bind:this={mapContainer} class="w-full h-full"></div>
</div>

<style>
  :global(.leaflet-container) {
    font-family: inherit;
  }
  :global(.marker-start), :global(.marker-end) {
    background: transparent;
    border: none;
  }
</style>

// src/components/RouteViewer.tsx
'use client';

import { useEffect, useRef } from 'react';
import { MapContainer, TileLayer, Polyline, Marker, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';

const startIcon = new L.Icon({
  iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
  iconSize: [25, 41],
  iconAnchor: [12, 41],
  popupAnchor: [1, -34],
  shadowSize: [41, 41]
});

const endIcon = new L.Icon({
  iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
  iconSize: [25, 41],
  iconAnchor: [12, 41],
  popupAnchor: [1, -34],
  shadowSize: [41, 41]
});

function FitBounds({ coordinates }: { coordinates: [number, number][] }) {
  const map = useMap();
  
  useEffect(() => {
    if (coordinates.length > 0) {
      const bounds = L.latLngBounds(coordinates);
      map.fitBounds(bounds, { padding: [50, 50] });
    }
  }, [coordinates, map]);
  
  return null;
}

interface RouteViewerProps {
  routeGeoJson: string | null;
  raceName: string;
}

export default function RouteViewer({ routeGeoJson, raceName }: RouteViewerProps) {
  const coordinates: [number, number][] = [];
  
  useEffect(() => {
    if (routeGeoJson) {
      try {
        const parsed = JSON.parse(routeGeoJson);
        if (Array.isArray(parsed)) {
          parsed.forEach((coord: number[]) => {
            if (coord.length >= 2) {
              coordinates.push([coord[0], coord[1]]);
            }
          });
        }
      } catch {
        console.error('Error parsing routeGeoJson');
      }
    }
  }, [routeGeoJson]);

  if (!routeGeoJson || coordinates.length === 0) {
    return null;
  }

  const center: [number, number] = coordinates.length > 0 
    ? coordinates[Math.floor(coordinates.length / 2)]
    : [9.0, -79.5];

  return (
    <div className="w-full h-96 rounded-lg overflow-hidden">
      <MapContainer 
        center={center} 
        zoom={13} 
        style={{ height: '100%', width: '100%' }}
      >
        <TileLayer
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
        <FitBounds coordinates={coordinates} />
        
        <Polyline 
          positions={coordinates} 
          color="#FF6B00" 
          weight={4}
          opacity={0.8}
        />
        <Marker position={coordinates[0]} icon={startIcon} />
        <Marker position={coordinates[coordinates.length - 1]} icon={endIcon} />
      </MapContainer>
    </div>
  );
}
